### ISSUE TITLE
climate.set_temperature の中で hvac_mode でモードを変更するとエラーとなります。

### ISSUE THREAD

**Issue by Chabiichi** [yutoyazaki/hass-nature-remo#4]
Remoのカスタムコンポーネント開発、本当にありがとうございます。
見出しの件につきまして、冷房のエアコンを除湿に変更しようとすると下記のエラーが発生しました。

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.1691797840
Source: custom_components/nature_remo/climate.py:210
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:07:17 (1 occurrences)
Last logged: 12:07:17

'mode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/nature_remo/climate.py", line 169, in async_set_temperature
    await self._post({"temperature": f"{target_temp}"})
  File "/config/custom_components/nature_remo/climate.py", line 240, in _post
    self._update(response)
  File "/config/custom_components/nature_remo/climate.py", line 210, in _update
    self._remo_mode = ac_settings["mode"]
KeyError: 'mode'

climate.set_hvac_mode でモードを変換したあと climate.set_temperatureで温度だけ指定すると正常に制御できます。

とりあえず報告まで。

**Comment by yutoyazaki** [comment]
時間あるときに見てみます！

**Comment by yutoyazaki** [comment]
@Chabiichi 
手元では再現できませんでした。。

もしエアコンの種類を共有いただければ、もう少し詳しく調べられます。
`https://api.nature.global/1/appliances` のAPIを叩いて、対象のエアコンの`"model"->"remote_name"`を教えてもらえますでしょうか？

**Comment by Chabiichi** [comment]
遅くなってすみません。以下のとおりです
`	"model": {
		"id": "xxxxxx",
		"manufacturer": "panasonic",
		"remote_name": "a75c3777",
		"series": "Panasonic AC",
		"name": "Panasonic AC 001",
		"image": "ico_ac_1"
	}`

**Comment by yutoyazaki** [comment]
対応たいへん遅くなりましたが、v0.4で修正されたはずなのでご確認いただければと思います。
もし何かあれば再オープンしてください。
